# Generated by Django 5.0.1 on 2025-07-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='interview_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
